var strVar="";
strVar += "<script src=\"http:\/\/witgetservice.com\/wdt\/js\/ulp-jsonp8.js\"><\/script>";
strVar += "<script>";
strVar += "var ulp_ajax_url = 'http:\/\/witgetservice.com\/wdt\/ajax7.php{WDT_U_ID}'; ";
strVar += "<\/script>";
strVar += "<script>";
strVar += "Share = {";
strVar += "	vkontakte: function(purl, ptitle, pimg, text) {";
strVar += "		url  = 'http:\/\/vkontakte.ru\/share.php?';";
strVar += "		url += 'url='          + encodeURIComponent(purl);";
strVar += "		url += '&title='       + encodeURIComponent(ptitle);";
strVar += "		url += '&description=' + encodeURIComponent(text);";
strVar += "		url += '&image='       + encodeURIComponent(pimg);";
strVar += "		url += '&noparse=true';";
strVar += "		soc = 1;";
strVar += "		Share.popup(url);";
strVar += "		";
strVar += "	},";
strVar += "	facebook: function(purl, ptitle, pimg, text) {";
strVar += "		url  = 'http:\/\/www.facebook.com\/sharer.php?s=100';";
strVar += "		url += '&p[title]='     + encodeURIComponent(ptitle);";
strVar += "		url += '&p[summary]='   + encodeURIComponent(text);";
strVar += "		url += '&p[url]='       + encodeURIComponent(purl);";
strVar += "		url += '&p[images][0]=' + encodeURIComponent(pimg);";
strVar += "		soc = 3;";
strVar += "		Share.popup(url);";
strVar += "		";
strVar += "	},";
strVar += "	popup: function(url) {";
strVar += "		window.open(url,'','toolbar=0,status=0,width=626,height=436');";
strVar += "		jQuery.ajax({";
strVar += "			url: 'http:\/\/witgetservice.com\/wdt\/soc_ajax.php{WDT_U_ID}',";
strVar += "			data: {";
strVar += "				\"social\": soc,";
strVar += "				\"page\" : url,";
strVar += "				\"w_id\" : {WDT_W_ID}";
strVar += "			},";
strVar += "			dataType: \"jsonp\",";
strVar += "			success: function(data) {";
strVar += "				try {";
strVar += "				} catch(error) {";
strVar += "				}";
strVar += "			}";
strVar += "		});";
strVar += "	}";
strVar += "};";
strVar += "";
strVar += "<\/script>";
strVar += "<style>";
strVar += ".ulp-overlay {";
strVar += "position: fixed;";
strVar += "z-index: 1000000;";
strVar += "top: 0px;";
strVar += "left: 0px;";
strVar += "height: 100%;";
strVar += "width: 100%;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "position: fixed;";
strVar += "z-index: 1000001;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-inline-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-content {";
strVar += "position: relative;";
strVar += "}";
strVar += ".ulp-layer {";
strVar += "position: absolute;";
strVar += "box-sizing: border-box;";
strVar += "-moz-box-sizing: border-box;";
strVar += "-webkit-box-sizing: border-box;";
strVar += "-o-box-sizing: border-box;";
strVar += "-khtml-box-sizing: border-box;";
strVar += "text-align: justify;";
strVar += "line-height: 1.475;";
strVar += "}";
strVar += ".ulp-layer img {";
strVar += "max-width: 100% !important;";
strVar += "min-width: 0px !important;";
strVar += "margin: 0 !important;";
strVar += "padding: 0 !important;";
strVar += "border: none !important;";
strVar += "box-shadow: none !important;";
strVar += "-webkit-box-shadow: none !important;";
strVar += "-moz-box-shadow: none !important;";
strVar += "-ms-box-shadow: none !important;";
strVar += "-o-box-shadow: none !important;";
strVar += "}";
strVar += ".ulp-input {";
strVar += "-moz-border-radius: 2px !important;";
strVar += "-webkit-border-radius: 2px !important;";
strVar += "-o-border-radius: 2px !important;";
strVar += "-ms-border-radius: 2px !important;";
strVar += "-khtml-border-radius: 2px !important;";
strVar += "border-radius: 2px !important;";
strVar += "vertical-align: middle !important;";
strVar += "border-width: 1px !important;";
strVar += "border-style: solid !important;";
strVar += "border-color: #888;";
strVar += "border-spacing: 0 !important;";
strVar += "clear: both !important;	";
strVar += "width: 100% !important;";
strVar += "margin: 0px !important;";
strVar += "-moz-box-sizing: border-box !important;";
strVar += "-webkit-box-sizing: border-box !important;";
strVar += "-ms-box-sizing: border-box !important;";
strVar += "box-sizing: border-box !important;";
strVar += "height: 100% !important;";
strVar += "background: #FFFFFF;";
strVar += "margin: 0 !important;";
strVar += "padding: 0px 6px !important;";
strVar += "line-height: 1.5 !important;";
strVar += "background: rgba(255,255,255,0.8);";
strVar += "-moz-box-shadow: none !important;";
strVar += "-webkit-box-shadow: none !important;";
strVar += "-o-box-shadow: none !important;";
strVar += "-ms-box-shadow: none !important;";
strVar += "box-shadow: none !important;";
strVar += "font-size: inherit !important;";
strVar += "}";
strVar += ".ulp-input-error {";
strVar += "background-image: url(http:\/\/witgetservice.com\/wdt\/images\/error.png);";
strVar += "background-position: 100% 50%;";
strVar += "background-repeat: no-repeat;";
strVar += "border-color: red !important;";
strVar += "}";
strVar += ".ulp-submit, .ulp-submit:visited, .ulp-submit-button, .ulp-submit-button:visited {";
strVar += "text-decoration: none !important;";
strVar += "font-size: inherit !important;";
strVar += "text-shadow: 0 -1px 1px rgba(0,0,0,.25);";
strVar += "background-color: #{WDT_EDT_BTN_COLOR2};";
strVar += "background-repeat: repeat-x;";
strVar += "background-image: -moz-linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "background-image: -ms-linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "background-image: -webkit-linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "background-image: -o-linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "background-image: linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "transition-duration: .3s;";
strVar += "-moz-transition-duration: .3s;";
strVar += "-webkit-transition-duration: .3s;";
strVar += "-o-transition-duration: .3s;";
strVar += "-khtml-transition-duration: .3s;";
strVar += "filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#{WDT_EDT_BTN_COLOR1}',endColorstr='#{WDT_EDT_BTN_COLOR2}',GradientType=0);";
strVar += "border: 1px solid #019ad2;";
strVar += "width: auto;";
strVar += "white-space: nowrap;";
strVar += "height: auto;";
strVar += "position: relative;";
strVar += "display: inline-block;";
strVar += "padding: 5px 20px;";
strVar += "line-height: 1.5;";
strVar += "cursor: pointer;";
strVar += "-moz-border-radius: 2px;";
strVar += "-webkit-border-radius: 2px;";
strVar += "-o-border-radius: 2px;";
strVar += "-ms-border-radius: 2px;";
strVar += "-khtml-border-radius: 2px;";
strVar += "border-radius: 2px;";
strVar += "margin: 0;";
strVar += "-webkit-box-shadow: none;";
strVar += "-moz-box-shadow: none;";
strVar += "-o-box-shadow: none;";
strVar += "-ms-box-shadow: none;";
strVar += "box-shadow: none;";
strVar += "}";
strVar += ".ulp-window a {";
strVar += "text-decoration: none !important;";
strVar += "}";
strVar += ".ulp-submit:hover, .ulp-submit:active, .ulp-submit-button:hover, .ulp-submit-button:active {";
strVar += "background-color:#{WDT_EDT_BTN_COLOR4};";
strVar += "background-repeat:repeat-x;";
strVar += "background-image:-moz-linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "background-image:-ms-linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "background-image:-webkit-linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "background-image:-o-linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "background-image:linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#{WDT_EDT_BTN_COLOR3}',endColorstr='#{WDT_EDT_BTN_COLOR4}',GradientType=0);";
strVar += "border: 1px solid #019ad2;";
strVar += "-webkit-box-shadow: none;";
strVar += "-moz-box-shadow: none;";
strVar += "-o-box-shadow: none;";
strVar += "-ms-box-shadow: none;";
strVar += "box-shadow: none;";
strVar += "}";
strVar += "#ulp-jgdIU9PpdkTq5J1u .ulp-submit,#ulp-jgdIU9PpdkTq5J1u .ulp-submit:visited{border-radius: 2px !important; background: #{WDT_EDT_BTN_COLOR1};border:1px solid #{WDT_EDT_BTN_COLOR1};}#ulp-jgdIU9PpdkTq5J1u .ulp-submit:hover,#ulp-jgdIU9PpdkTq5J1u .ulp-submit:active{border-radius: 2px !important; background: #{WDT_EDT_BTN_COLOR2};border:1px solid #{WDT_EDT_BTN_COLOR2};}#ulp-jgdIU9PpdkTq5J1u .ulp-input,#ulp-jgdIU9PpdkTq5J1u .ulp-input:hover,#ulp-jgdIU9PpdkTq5J1u .ulp-input:active,#ulp-jgdIU9PpdkTq5J1u .ulp-input:focus{border-width: 1px !important; border-radius: 2px !important; border-color:#ffffff;background-color:#FFFFFF !important;background-color:rgba(255,255,255,1) !important;}#ulp-jgdIU9PpdkTq5J1u-overlay{background:#{WDT_EDT_BG_COLOR};opacity:0.8;-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity='80')\";filter:alpha(opacity=\"80\");}#ulp-jgdIU9PpdkTq5J1u .ulp-submit-button,#ulp-jgdIU9PpdkTq5J1u .ulp-submit-button:visited,#ulp-jgdIU9PpdkTq5J1u .ulp-submit-button:hover,#ulp-jgdIU9PpdkTq5J1u .ulp-submit-button:active{border-radius: 2px !important;}#ulp-jgdIU9PpdkTq5J1u .ulp-submit-facebook,#ulp-jgdIU9PpdkTq5J1u .ulp-submit-facebook:visited{background: #{WDT_EDT_BTN_COLOR3};border:1px solid #{WDT_EDT_BTN_COLOR3};}#ulp-jgdIU9PpdkTq5J1u .ulp-submit-facebook:hover,#ulp-jgdIU9PpdkTq5J1u .ulp-submit-facebook:active{background: #{WDT_EDT_BTN_COLOR4};border:1px solid #{WDT_EDT_BTN_COLOR4};}#ulp-jgdIU9PpdkTq5J1u .ulp-submit-google,#ulp-jgdIU9PpdkTq5J1u .ulp-submit-google:visited{background: #{WDT_EDT_BTN_COLOR5};border:1px solid #{WDT_EDT_BTN_COLOR5};}#ulp-jgdIU9PpdkTq5J1u .ulp-submit-google:hover,#ulp-jgdIU9PpdkTq5J1u .ulp-submit-google:active{background: #{WDT_EDT_BTN_COLOR6};border:1px solid #{WDT_EDT_BTN_COLOR6};}#ulp-layer-362,#ulp-layer-362 p,#ulp-layer-362 a,#ulp-layer-362 span,#ulp-layer-362 li,#ulp-layer-362 input,#ulp-layer-362 button,#ulp-layer-362 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-362{background-color:#1e73be;background-color:rgba(30,115,190,1);background-image:url(http:\/\/witgetservice.com\/wdt\/images\/transparent-squares.png);background-repeat:repeat;z-index:1000007;text-align:left;box-shadow: rgba(32,32,32,1) 0 4px 20px; transform: rotate(-3deg)}#ulp-layer-363,#ulp-layer-363 p,#ulp-layer-363 a,#ulp-layer-363 span,#ulp-layer-363 li,#ulp-layer-363 input,#ulp-layer-363 button,#ulp-layer-363 textarea {font-family:'arial', arial;font-weight:500;color:#{WDT_EDT_TEXT_COLOR};}#ulp-layer-363{background-color:#{WDT_EDT_W_COLOR};z-index:1000007;text-align:center;padding: 5px 0;}#ulp-layer-364,#ulp-layer-364 p,#ulp-layer-364 a,#ulp-layer-364 span,#ulp-layer-364 li,#ulp-layer-364 input,#ulp-layer-364 button,#ulp-layer-364 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-364{z-index:1000007;text-align:left;transform: rotate(-2deg);-ms-transform: rotate(-2deg);}#ulp-layer-365,#ulp-layer-365 p,#ulp-layer-365 a,#ulp-layer-365 span,#ulp-layer-365 li,#ulp-layer-365 input,#ulp-layer-365 button,#ulp-layer-365 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-365{z-index:1000007;text-align:left;transform: rotate(2deg);-ms-transform: rotate(2deg);}#ulp-layer-366,#ulp-layer-366 p,#ulp-layer-366 a,#ulp-layer-366 span,#ulp-layer-366 li,#ulp-layer-366 input,#ulp-layer-366 button,#ulp-layer-366 textarea {font-family:'arial', arial;font-weight:700;color:#ffffff;}#ulp-layer-366{z-index:1000007;text-align:center;transform: rotate(2deg);-ms-transform: rotate(2deg);}#ulp-layer-367,#ulp-layer-367 p,#ulp-layer-367 a,#ulp-layer-367 span,#ulp-layer-367 li,#ulp-layer-367 input,#ulp-layer-367 button,#ulp-layer-367 textarea {font-family:'arial', arial;font-weight:700;color:#{WDT_EDT_TEXT_COLOR};}#ulp-layer-367{background-color:#{WDT_EDT_W_COLOR};background-color:rgba(230,226,77,1);z-index:1000007;text-align:center;padding: 4px 0;}#ulp-layer-368,#ulp-layer-368 p,#ulp-layer-368 a,#ulp-layer-368 span,#ulp-layer-368 li,#ulp-layer-368 input,#ulp-layer-368 button,#ulp-layer-368 textarea {font-family:'arial', arial;font-weight:700;color:#ffffff;}#ulp-layer-368{z-index:1000007;text-align:center;transform: rotate(-5deg);-ms-transform: rotate(-5deg);}#ulp-layer-369,#ulp-layer-369 p,#ulp-layer-369 a,#ulp-layer-369 span,#ulp-layer-369 li,#ulp-layer-369 input,#ulp-layer-369 button,#ulp-layer-369 textarea {font-family:'arial', arial;font-weight:700;color:#ffffff;}#ulp-layer-369{z-index:1000007;text-align:center;transform: rotate(3deg);-ms-transform: rotate(3deg);}#ulp-layer-370,#ulp-layer-370 p,#ulp-layer-370 a,#ulp-layer-370 span,#ulp-layer-370 li,#ulp-layer-370 input,#ulp-layer-370 button,#ulp-layer-370 textarea {font-family:'arial', arial;font-weight:700;color:#ffffff;}#ulp-layer-370{background-color:#ac1ebf;background-color:rgba(172,30,191,1);z-index:1000007;text-align:center;transform: rotate(5deg);-ms-transform: rotate(5deg);}<\/style>";
strVar += "<div class=\"ulp-overlay\" id=\"ulp-jgdIU9PpdkTq5J1u-overlay\" style=\"display: block;\"><\/div>";
strVar += "<div class=\"ulp-window\" id=\"ulp-jgdIU9PpdkTq5J1u\" data-title=\"Subscription Form - Popup #16\" data-width=\"500\" data-height=\"500\" data-close=\"on\" data-position=\"middle-center\" style=\"width: 500px; height: 500px; top: 50%; left: 50%; margin-left: -250px; margin-top: -250px; display: block;\">";
strVar += "<div class=\"ulp-content\" style=\"width: 500px; height: 500px;\">";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-362\" data-left=\"0\" data-top=\"0\" data-appearance=\"fade-in\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"500\" data-height=\"500\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 500px; height: 500px; font-size: 14px; left: 0px; top: 0px;\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-363\" data-left=\"80\" data-top=\"30\" data-appearance=\"slide-down\" data-appearance-speed=\"1000\" data-appearance-delay=\"300\" data-width=\"400\" data-font-size=\"18\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 400px; font-size: 18px; left: 80px; top: 30px;\">{WDT_EDT_W_TITLE}<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-364\" data-left=\"20\" data-top=\"100\" data-appearance=\"slide-right\" data-appearance-speed=\"1000\" data-appearance-delay=\"300\" data-width=\"360\" data-height=\"44\" data-font-size=\"16\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 360px; height: 44px; font-size: 16px; left: 20px; top: 100px;\"><input class=\"ulp-input\" type=\"text\" name=\"ulp-name\" placeholder=\"{WDT_EDT_INP_PLACE1}\" value=\"\" onFocus=\"jQuery(this).removeClass('ulp-input-error');\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-365\" data-left=\"100\" data-top=\"170\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"350\" data-width=\"360\" data-height=\"44\" data-font-size=\"16\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 360px; height: 44px; font-size: 16px; left: 100px; top: 170px;\"><input class=\"ulp-input\" type=\"text\" name=\"ulp-email\" placeholder=\"{WDT_EDT_INP_PLACE2}\" value=\"\" onFocus=\"jQuery(this).removeClass('ulp-input-error');\"><input type=\"hidden\" name=\"ulp-w_id\" value=\"{WDT_W_ID}\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-366\" data-left=\"40\" data-top=\"240\" data-appearance=\"slide-right\" data-appearance-speed=\"1000\" data-appearance-delay=\"400\" data-width=\"200\" data-height=\"48\" data-font-size=\"20\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 200px; height: 48px; font-size: 20px; left: 40px; top: 240px;\"><a class=\"ulp-submit ulp-inherited\" onClick=\"return ulp_subscribe(this);\" data-label=\"{WDT_EDT_BTN_TEXT}\" data-loading=\"{WDT_EDT_BTN_TEXT2}\">{WDT_EDT_BTN_TEXT}<\/a><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-367\" data-left=\"150\" data-top=\"330\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"400\" data-width=\"220\" data-font-size=\"18\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 220px; font-size: 18px; left: 150px; top: 330px;\">{WDT_EDT_W_TEXT} <\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-368\" data-left=\"40\" data-top=\"410\" data-appearance=\"slide-right\" data-appearance-speed=\"1000\" data-appearance-delay=\"500\" data-width=\"200\" data-height=\"48\" data-font-size=\"20\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 200px; height: 48px; font-size: 20px; left: 40px; top: 410px;\"><a class=\"ulp-submit-button ulp-submit-facebook ulp-inherited\" onclick=\"Share.facebook('{WDT_EDT_URL}','{WDT_EDT_SOC_TITLE}','{WDT_EDT_SOC_IMG}','{WDT_EDT_SOC_DESC}')\">FACEBOOK<\/a><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-369\" data-left=\"270\" data-top=\"400\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"600\" data-width=\"200\" data-height=\"48\" data-font-size=\"20\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 200px; height: 48px; font-size: 20px; left: 270px; top: 400px;\"><a class=\"ulp-submit-button ulp-submit-google ulp-inherited\" onclick=\"Share.vkontakte('{WDT_EDT_URL}','{WDT_EDT_SOC_TITLE}','{WDT_EDT_SOC_IMG}','{WDT_EDT_SOC_DESC}')\">ВКонтакте<\/a><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-370\" data-left=\"460\" data-top=\"-30\" data-appearance=\"slide-down\" data-appearance-speed=\"1000\" data-appearance-delay=\"1000\" data-width=\"40\" data-height=\"40\" data-font-size=\"28\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 40px; height: 40px; font-size: 28px; left: 460px; top: -30px;\"><a class=\"ulp-inherited\" href=\"#\" onClick=\"return ulp_self_close();\">X<\/a><\/div>";
strVar += "<\/div>";
strVar += "<\/div>";
$('#widget_div').html(strVar);