var strVar="";
strVar += "<script src=\"http:\/\/witgetservice.com\/wdt\/js\/ulp-jsonp14.js\"><\/script>";
strVar += "<script>";
strVar += "var ulp_ajax_url = 'http:\/\/witgetservice.com\/wdt\/ajax.php{WDT_U_ID}'; ";
strVar += "<\/script>";
strVar += "";
strVar += "<style>";
strVar += ".ulp-overlay {";
strVar += "position: fixed;";
strVar += "z-index: 1000000;";
strVar += "top: 0px;";
strVar += "left: 0px;";
strVar += "height: 100%;";
strVar += "width: 100%;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "position: fixed;";
strVar += "z-index: 1000001;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-inline-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-content {";
strVar += "position: relative;";
strVar += "}";
strVar += ".ulp-layer {";
strVar += "position: absolute;";
strVar += "box-sizing: border-box;";
strVar += "-moz-box-sizing: border-box;";
strVar += "-webkit-box-sizing: border-box;";
strVar += "-o-box-sizing: border-box;";
strVar += "-khtml-box-sizing: border-box;";
strVar += "text-align: justify;";
strVar += "line-height: 1.475;";
strVar += "}";
strVar += ".ulp-layer img {";
strVar += "max-width: 100% !important;";
strVar += "min-width: 0px !important;";
strVar += "margin: 0 !important;";
strVar += "padding: 0 !important;";
strVar += "border: none !important;";
strVar += "box-shadow: none !important;";
strVar += "-webkit-box-shadow: none !important;";
strVar += "-moz-box-shadow: none !important;";
strVar += "-ms-box-shadow: none !important;";
strVar += "-o-box-shadow: none !important;";
strVar += "}";
strVar += ".ulp-input {";
strVar += "-moz-border-radius: 2px !important;";
strVar += "-webkit-border-radius: 2px !important;";
strVar += "-o-border-radius: 2px !important;";
strVar += "-ms-border-radius: 2px !important;";
strVar += "-khtml-border-radius: 2px !important;";
strVar += "border-radius: 2px !important;";
strVar += "vertical-align: middle !important;";
strVar += "border-width: 1px !important;";
strVar += "border-style: solid !important;";
strVar += "border-color: #888;";
strVar += "border-spacing: 0 !important;";
strVar += "clear: both !important;	";
strVar += "width: 100% !important;";
strVar += "margin: 0px !important;";
strVar += "-moz-box-sizing: border-box !important;";
strVar += "-webkit-box-sizing: border-box !important;";
strVar += "-ms-box-sizing: border-box !important;";
strVar += "box-sizing: border-box !important;";
strVar += "height: 100% !important;";
strVar += "background: #FFFFFF;";
strVar += "margin: 0 !important;";
strVar += "padding: 0px 6px !important;";
strVar += "line-height: 1.5 !important;";
strVar += "background: rgba(255,255,255,0.8);";
strVar += "-moz-box-shadow: none !important;";
strVar += "-webkit-box-shadow: none !important;";
strVar += "-o-box-shadow: none !important;";
strVar += "-ms-box-shadow: none !important;";
strVar += "box-shadow: none !important;";
strVar += "font-size: inherit !important;";
strVar += "}";
strVar += ".ulp-input-error {";
strVar += "background-image: url(http:\/\/witgetservice.com\/wdt\/images\/error.png);";
strVar += "background-position: 100% 50%;";
strVar += "background-repeat: no-repeat;";
strVar += "border-color: red !important;";
strVar += "}";
strVar += ".ulp-submit, .ulp-submit:visited, .ulp-submit-button, .ulp-submit-button:visited {";
strVar += "text-decoration: none !important;";
strVar += "font-size: inherit !important;";
strVar += "text-shadow: 0 -1px 1px rgba(0,0,0,.25);";
strVar += "background-color: #019ad2;";
strVar += "background-repeat: repeat-x;";
strVar += "background-image: -moz-linear-gradient(#33bcef,#019ad2);";
strVar += "background-image: -ms-linear-gradient(#33bcef,#019ad2);";
strVar += "background-image: -webkit-linear-gradient(#33bcef,#019ad2);";
strVar += "background-image: -o-linear-gradient(#33bcef,#019ad2);";
strVar += "background-image: linear-gradient(#33bcef,#019ad2);";
strVar += "transition-duration: .3s;";
strVar += "-moz-transition-duration: .3s;";
strVar += "-webkit-transition-duration: .3s;";
strVar += "-o-transition-duration: .3s;";
strVar += "-khtml-transition-duration: .3s;";
strVar += "filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#33bcef',endColorstr='#019ad2',GradientType=0);";
strVar += "border: 1px solid #019ad2;";
strVar += "width: auto;";
strVar += "white-space: nowrap;";
strVar += "height: auto;";
strVar += "position: relative;";
strVar += "display: inline-block;";
strVar += "padding: 5px 20px;";
strVar += "line-height: 1.5;";
strVar += "cursor: pointer;";
strVar += "-moz-border-radius: 2px;";
strVar += "-webkit-border-radius: 2px;";
strVar += "-o-border-radius: 2px;";
strVar += "-ms-border-radius: 2px;";
strVar += "-khtml-border-radius: 2px;";
strVar += "border-radius: 2px;";
strVar += "margin: 0;";
strVar += "-webkit-box-shadow: none;";
strVar += "-moz-box-shadow: none;";
strVar += "-o-box-shadow: none;";
strVar += "-ms-box-shadow: none;";
strVar += "box-shadow: none;";
strVar += "}";
strVar += ".ulp-window a {";
strVar += "text-decoration: none !important;";
strVar += "}";
strVar += ".ulp-submit:hover, .ulp-submit:active, .ulp-submit-button:hover, .ulp-submit-button:active {";
strVar += "background-color:#0271bf;";
strVar += "background-repeat:repeat-x;";
strVar += "background-image:-moz-linear-gradient(#2daddc,#0271bf);";
strVar += "background-image:-ms-linear-gradient(#2daddc,#0271bf);";
strVar += "background-image:-webkit-linear-gradient(#2daddc,#0271bf);";
strVar += "background-image:-o-linear-gradient(#2daddc,#0271bf);";
strVar += "background-image:linear-gradient(#2daddc,#0271bf);";
strVar += "filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#2daddc',endColorstr='#0271bf',GradientType=0);";
strVar += "border: 1px solid #019ad2;";
strVar += "-webkit-box-shadow: none;";
strVar += "-moz-box-shadow: none;";
strVar += "-o-box-shadow: none;";
strVar += "-ms-box-shadow: none;";
strVar += "box-shadow: none;";
strVar += "}";
strVar += "#ulp-8RDTcFM2mszLzQIs .ulp-submit,#ulp-8RDTcFM2mszLzQIs .ulp-submit:visited{border-radius: 2px !important; background: #{WDT_EDT_BTN_COLOR1};border:1px solid #{WDT_EDT_BTN_COLOR1};background-image:linear-gradient(#{WDT_EDT_BTN_COLOR2},#{WDT_EDT_BTN_COLOR1});}#ulp-8RDTcFM2mszLzQIs .ulp-submit:hover,#ulp-8RDTcFM2mszLzQIs .ulp-submit:active{border-radius: 2px !important; background: #{WDT_EDT_BTN_COLOR3};border:1px solid #{WDT_EDT_BTN_COLOR3};background-image:linear-gradient(#{WDT_EDT_BTN_COLOR4},#{WDT_EDT_BTN_COLOR3});}#ulp-8RDTcFM2mszLzQIs .ulp-input,#ulp-8RDTcFM2mszLzQIs .ulp-input:hover,#ulp-8RDTcFM2mszLzQIs .ulp-input:active,#ulp-8RDTcFM2mszLzQIs .ulp-input:focus{border-width: 1px !important; border-radius: 2px !important; border-color:#ffffff;background-color:#ffffff !important;background-color:rgba(255,255,255,1) !important;}#ulp-8RDTcFM2mszLzQIs-overlay{background:#{WDT_EDT_BG_COLOR};opacity:0.8;-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity='80')\";filter:alpha(opacity=\"80\");}#ulp-8RDTcFM2mszLzQIs .ulp-submit-button,#ulp-8RDTcFM2mszLzQIs .ulp-submit-button:visited,#ulp-8RDTcFM2mszLzQIs .ulp-submit-button:hover,#ulp-8RDTcFM2mszLzQIs .ulp-submit-button:active{border-radius: 2px !important;}#ulp-8RDTcFM2mszLzQIs .ulp-submit-facebook,#ulp-8RDTcFM2mszLzQIs .ulp-submit-facebook:visited{background: #3b5998;border:1px solid #3b5998;background-image:linear-gradient(#324b80,#3b5998);}#ulp-8RDTcFM2mszLzQIs .ulp-submit-facebook:hover,#ulp-8RDTcFM2mszLzQIs .ulp-submit-facebook:active{background: #324b80;border:1px solid #3b5998;background-image:linear-gradient(#3b5998,#324b80);}#ulp-8RDTcFM2mszLzQIs .ulp-submit-google,#ulp-8RDTcFM2mszLzQIs .ulp-submit-google:visited{background: #d34836;border:1px solid #d34836;background-image:linear-gradient(#b53e2f,#d34836);}#ulp-8RDTcFM2mszLzQIs .ulp-submit-google:hover,#ulp-8RDTcFM2mszLzQIs .ulp-submit-google:active{background: #b53e2f;border:1px solid #d34836;background-image:linear-gradient(#d34836,#b53e2f);}#ulp-layer-83,#ulp-layer-83 p,#ulp-layer-83 a,#ulp-layer-83 span,#ulp-layer-83 li,#ulp-layer-83 input,#ulp-layer-83 button,#ulp-layer-83 textarea {font-family:'arial', arial;font-weight:700;color:#{WDT_EDT_TEXT_COLOR};}#ulp-layer-83{background-color:#34495e;background-color:rgba(52,73,94,0.9);z-index:1000007;text-align:left;padding: 5px 15px; box-shadow: rgba(32,32,32,0.3) 0 4px 20px;}#ulp-layer-84,#ulp-layer-84 p,#ulp-layer-84 a,#ulp-layer-84 span,#ulp-layer-84 li,#ulp-layer-84 input,#ulp-layer-84 button,#ulp-layer-84 textarea {font-family:'arial', arial;font-weight:700;color:#ffffff;}#ulp-layer-84{background-color:#e33a0c;background-color:rgba(227,58,12,1);z-index:1000003;text-align:left;box-shadow: rgba(32,32,32,0.3) 0 4px 20px;}#ulp-layer-85,#ulp-layer-85 p,#ulp-layer-85 a,#ulp-layer-85 span,#ulp-layer-85 li,#ulp-layer-85 input,#ulp-layer-85 button,#ulp-layer-85 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-85{z-index:1000007;text-align:left;}#ulp-layer-86,#ulp-layer-86 p,#ulp-layer-86 a,#ulp-layer-86 span,#ulp-layer-86 li,#ulp-layer-86 input,#ulp-layer-86 button,#ulp-layer-86 textarea {font-family:'arial', arial;font-weight:700;color:#ffffff;}#ulp-layer-86{background-color:#f39c12;background-color:rgba(243,156,18,1);z-index:1000003;text-align:left;box-shadow: rgba(32,32,32,0.3) 0 4px 20px;}#ulp-layer-87,#ulp-layer-87 p,#ulp-layer-87 a,#ulp-layer-87 span,#ulp-layer-87 li,#ulp-layer-87 input,#ulp-layer-87 button,#ulp-layer-87 textarea {font-family:'arial', arial;font-weight:400;color:#000000;text-shadow: #ffffff 1px 1px 1px;}#ulp-layer-87{z-index:1000007;text-align:left;}#ulp-layer-88,#ulp-layer-88 p,#ulp-layer-88 a,#ulp-layer-88 span,#ulp-layer-88 li,#ulp-layer-88 input,#ulp-layer-88 button,#ulp-layer-88 textarea {font-family:'arial', arial;font-weight:700;color:#ffffff;}#ulp-layer-88{background-color:#663777;background-color:rgba(102,55,119,1);z-index:1000003;text-align:left;box-shadow: rgba(32,32,32,0.3) 0 4px 20px;}#ulp-layer-89,#ulp-layer-89 p,#ulp-layer-89 a,#ulp-layer-89 span,#ulp-layer-89 li,#ulp-layer-89 input,#ulp-layer-89 button,#ulp-layer-89 textarea {font-family:'arial', arial;font-weight:400;color:#000000;text-shadow: #ffffff 1px 1px 1px;}#ulp-layer-89{z-index:1000007;text-align:left;}#ulp-layer-90,#ulp-layer-90 p,#ulp-layer-90 a,#ulp-layer-90 span,#ulp-layer-90 li,#ulp-layer-90 input,#ulp-layer-90 button,#ulp-layer-90 textarea {font-family:'arial', arial;font-weight:400;color:#ffffff;}#ulp-layer-90{z-index:1000007;text-align:center;}#ulp-layer-91,#ulp-layer-91 p,#ulp-layer-91 a,#ulp-layer-91 span,#ulp-layer-91 li,#ulp-layer-91 input,#ulp-layer-91 button,#ulp-layer-91 textarea {font-family:'arial', arial;font-weight:400;color:#ffffff;text-shadow: #000000 1px 1px 1px;}#ulp-layer-91{z-index:1000007;text-align:right;}#ulp-layer-92,#ulp-layer-92 p,#ulp-layer-92 a,#ulp-layer-92 span,#ulp-layer-92 li,#ulp-layer-92 input,#ulp-layer-92 button,#ulp-layer-92 textarea {font-family:'arial', arial;font-weight:400;color:#ffffff;}#ulp-layer-92{background-color:#2a7536;background-color:rgba(42,117,54,1);z-index:1000007;text-align:center;padding: 5px 0; box-shadow: rgba(32,32,32,0.3) 0 4px 20px;}<\/style>";
strVar += "<div class=\"ulp-overlay\" id=\"ulp-8RDTcFM2mszLzQIs-overlay\" style=\"display: block;\"><\/div>";
strVar += "<div class=\"ulp-window\" id=\"ulp-8RDTcFM2mszLzQIs\" data-title=\"Contact Form - Popup #08\" data-width=\"700\" data-height=\"400\" data-close=\"on\" data-position=\"middle-center\" style=\"width: 700px; height: 400px; top: 50%; left: 50%; margin-left: -350px; margin-top: -200px; display: block;\">";
strVar += "<div class=\"ulp-content\" style=\"width: 700px; height: 400px;\">";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-83\" data-left=\"20\" data-top=\"0\" data-appearance=\"slide-down\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-font-size=\"24\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"font-size: 24px; left: 20px; top: 0px;\">{WDT_EDT_TITLE}<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-84\" data-left=\"200\" data-top=\"60\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"400\" data-height=\"60\" data-font-size=\"24\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 400px; height: 60px; font-size: 24px; left: 200px; top: 60px;\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-85\" data-left=\"215\" data-top=\"72\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"370\" data-height=\"36\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 370px; height: 36px; font-size: 14px; left: 215px; top: 72px;\">";
strVar += "<input type=\"hidden\" name=\"ulp-msg_id\" value=\"{WDT_MSG_ID}\">";
strVar += "<input type=\"hidden\" name=\"ulp-msg_theme\" value=\"{WDT_MSG_THEME}\">";
strVar += "<input type=\"hidden\" name=\"ulp-w_id\" value=\"{WDT_W_ID}\">";
strVar += "<input class=\"ulp-input\" type=\"text\" name=\"ulp-name\" placeholder=\"{WDT_EDT_INP_PLACE1}\" value=\"\" onfocus=\"jQuery(this).removeClass('ulp-input-error');\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-86\" data-left=\"50\" data-top=\"130\" data-appearance=\"slide-right\" data-appearance-speed=\"1000\" data-appearance-delay=\"400\" data-width=\"400\" data-height=\"60\" data-font-size=\"24\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 400px; height: 60px; font-size: 24px; left: 50px; top: 130px;\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-87\" data-left=\"65\" data-top=\"142\" data-appearance=\"slide-right\" data-appearance-speed=\"1000\" data-appearance-delay=\"400\" data-width=\"370\" data-height=\"36\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 370px; height: 36px; font-size: 14px; left: 65px; top: 142px;\"><input class=\"ulp-input\" type=\"text\" name=\"ulp-email\" placeholder=\"{WDT_EDT_INP_PLACE2}\" value=\"\" onfocus=\"jQuery(this).removeClass('ulp-input-error');\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-88\" data-left=\"240\" data-top=\"200\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"600\" data-width=\"460\" data-height=\"160\" data-font-size=\"24\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 460px; height: 160px; font-size: 24px; left: 240px; top: 200px;\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-89\" data-left=\"255\" data-top=\"214\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"600\" data-width=\"430\" data-height=\"132\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 430px; height: 132px; font-size: 14px; left: 255px; top: 214px;\"><textarea class=\"ulp-input\" name=\"ulp-message\" placeholder=\"{WDT_EDT_INP_PLACE3}\" onfocus=\"jQuery(this).removeClass('ulp-input-error');\"><\/textarea><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-90\" data-left=\"0\" data-top=\"370\" data-appearance=\"slide-up\" data-appearance-speed=\"1000\" data-appearance-delay=\"800\" data-width=\"240\" data-height=\"38\" data-font-size=\"20\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 240px; height: 38px; font-size: 20px; left: 0px; top: 340px;\"><a class=\"ulp-submit\" onclick=\"return ulp_subscribe(this);\" data-label=\"{WDT_EDT_BTN_TEXT}\" data-loading=\"{WDT_EDT_BTN_TEXT2}\">{WDT_EDT_BTN_TEXT}<\/a><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-91\" data-left=\"660\" data-top=\"-30\" data-appearance=\"slide-down\" data-appearance-speed=\"1000\" data-appearance-delay=\"1000\" data-width=\"40\" data-height=\"20\" data-font-size=\"24\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 40px; height: 20px; font-size: 24px; left: 660px; top: -30px;\"><a href=\"#\" onclick=\"return ulp_self_close();\">×<\/a><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-92\" data-left=\"300\" data-top=\"370\" data-appearance=\"slide-left\" data-appearance-speed=\"600\" data-appearance-delay=\"0\" data-width=\"400\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"on\" style=\"display: none; width: 400px; font-size: 14px; left: 300px; top: 370px;\">{WDT_EDT_SUCCESS}<\/div>";
strVar += "<\/div>";
strVar += "<\/div>";

$('#widget_div').html(strVar);