var strVar="";
strVar += "<script src=\"http:\/\/witgetservice.com\/wdt\/js\/ulp-jsonp19.js\"><\/script>";
strVar += "<style>";
strVar += ".ulp-overlay {";
strVar += "position: fixed;";
strVar += "z-index: 1000000;";
strVar += "top: 0px;";
strVar += "left: 0px;";
strVar += "height: 100%;";
strVar += "width: 100%;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "position: fixed;";
strVar += "z-index: 1000001;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-inline-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-content {";
strVar += "position: relative;";
strVar += "}";
strVar += ".ulp-layer {";
strVar += "position: absolute;";
strVar += "box-sizing: border-box;";
strVar += "-moz-box-sizing: border-box;";
strVar += "-webkit-box-sizing: border-box;";
strVar += "-o-box-sizing: border-box;";
strVar += "-khtml-box-sizing: border-box;";
strVar += "text-align: justify;";
strVar += "line-height: 1.475;";
strVar += "}";
strVar += ".ulp-layer img {";
strVar += "max-width: 100% !important;";
strVar += "min-width: 0px !important;";
strVar += "margin: 0 !important;";
strVar += "padding: 0 !important;";
strVar += "border: none !important;";
strVar += "box-shadow: none !important;";
strVar += "-webkit-box-shadow: none !important;";
strVar += "-moz-box-shadow: none !important;";
strVar += "-ms-box-shadow: none !important;";
strVar += "-o-box-shadow: none !important;";
strVar += "}";
strVar += "#ulp-VM8Ug5gsrGeCQ59B .ulp-submit,#ulp-VM8Ug5gsrGeCQ59B .ulp-submit:visited{border-radius: 2px !important; background: #{WDT_EDT_BTN_COLOR1};border:1px solid #{WDT_EDT_BTN_COLOR1};background-image:linear-gradient(#{WDT_EDT_BTN_COLOR2},#{WDT_EDT_BTN_COLOR1}); padding:15px; text-decoration:none;}#ulp-VM8Ug5gsrGeCQ59B .ulp-submit:hover,#ulp-VM8Ug5gsrGeCQ59B .ulp-submit:active{border-radius: 2px !important; background: #{WDT_EDT_BTN_COLOR3};border:1px solid #{WDT_EDT_BTN_COLOR4};background-image:linear-gradient(#{WDT_EDT_BTN_COLOR4},#{WDT_EDT_BTN_COLOR3});}#ulp-VM8Ug5gsrGeCQ59B .ulp-input,#ulp-VM8Ug5gsrGeCQ59B .ulp-input:hover,#ulp-VM8Ug5gsrGeCQ59B .ulp-input:active,#ulp-VM8Ug5gsrGeCQ59B .ulp-input:focus{border-width: 1px !important; border-radius: 2px !important; border-color:#777777;background-color:#ffffff !important;background-color:rgba(255,255,255,0.5) !important;}#ulp-VM8Ug5gsrGeCQ59B-overlay{background:#{WDT_EDT_BG_COLOR};opacity:0.8;-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity='80')\";filter:alpha(opacity=\"80\");}#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-button,#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-button:visited,#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-button:hover,#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-button:active{border-radius: 2px !important;}#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-facebook,#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-facebook:visited{background: #3b5998;border:1px solid #3b5998;background-image:linear-gradient(#324b80,#3b5998);}#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-facebook:hover,#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-facebook:active{background: #324b80;border:1px solid #3b5998;background-image:linear-gradient(#3b5998,#324b80);}#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-google,#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-google:visited{background: #d34836;border:1px solid #d34836;background-image:linear-gradient(#b53e2f,#d34836);}#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-google:hover,#ulp-VM8Ug5gsrGeCQ59B .ulp-submit-google:active{background: #b53e2f;border:1px solid #d34836;background-image:linear-gradient(#d34836,#b53e2f);}#ulp-layer-442,#ulp-layer-442 p,#ulp-layer-442 a,#ulp-layer-442 span,#ulp-layer-442 li,#ulp-layer-442 input,#ulp-layer-442 button,#ulp-layer-442 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-442{background-color:#35c6f5;background-color:rgba(53,198,245,0.9);z-index:1000003;text-align:left;}#ulp-layer-443,#ulp-layer-443 p,#ulp-layer-443 a,#ulp-layer-443 span,#ulp-layer-443 li,#ulp-layer-443 input,#ulp-layer-443 button,#ulp-layer-443 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-443{z-index:1000003;text-align:left;}#ulp-layer-446,#ulp-layer-446 p,#ulp-layer-446 a,#ulp-layer-446 span,#ulp-layer-446 li,#ulp-layer-446 input,#ulp-layer-446 button,#ulp-layer-446 textarea {font-family:'verdana', arial;font-weight:700;color:#{WDT_EDT_TITLE_COLOR};text-shadow: #ffffff 1px 1px 1px;}#ulp-layer-446{z-index:1000007;text-align:justify;}#ulp-layer-447,#ulp-layer-447 p,#ulp-layer-447 a,#ulp-layer-447 span,#ulp-layer-447 li,#ulp-layer-447 input,#ulp-layer-447 button,#ulp-layer-447 textarea {font-family:'arial', arial;font-weight:400;color:#333333;text-shadow: #ffffff 1px 1px 1px;}#ulp-layer-447{z-index:1000007;text-align:justify;}#ulp-layer-448,#ulp-layer-448 p,#ulp-layer-448 a,#ulp-layer-448 span,#ulp-layer-448 li,#ulp-layer-448 input,#ulp-layer-448 button,#ulp-layer-448 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-448{z-index:1000007;text-align:left;}#ulp-layer-452,#ulp-layer-452 p,#ulp-layer-452 a,#ulp-layer-452 span,#ulp-layer-452 li,#ulp-layer-452 input,#ulp-layer-452 button,#ulp-layer-452 textarea {font-family:'arial', arial;font-weight:400;color:#ffffff;text-shadow: #000000 1px 1px 1px;}#ulp-layer-452{z-index:1000007;text-align:center;}#ulp-layer-454,#ulp-layer-454 p,#ulp-layer-454 a,#ulp-layer-454 span,#ulp-layer-454 li,#ulp-layer-454 input,#ulp-layer-454 button,#ulp-layer-454 textarea {font-family:'verdana', arial;font-weight:400;color:#a76b0e; text-decoration:none;}#ulp-layer-454{z-index:1000007;text-align:right;}#ulp-layer-455,#ulp-layer-455 p,#ulp-layer-455 a,#ulp-layer-455 span,#ulp-layer-455 li,#ulp-layer-455 input,#ulp-layer-455 button,#ulp-layer-455 textarea {font-family:'verdana', arial;font-weight:700;color:#{WDT_EDT_TEXT_COLOR};text-shadow: #166be8 1px 1px 1px;}#ulp-layer-455{z-index:1000007;text-align:center;}#ulp-layer-456,#ulp-layer-456 p,#ulp-layer-456 a,#ulp-layer-456 span,#ulp-layer-456 li,#ulp-layer-456 input,#ulp-layer-456 button,#ulp-layer-456 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-456{z-index:1000007;text-align:left;}<\/style>";
strVar += "<div class=\"ulp-overlay\" id=\"ulp-VM8Ug5gsrGeCQ59B-overlay\" style=\"display: block;\"><\/div>";
strVar += "<div class=\"ulp-window\" id=\"ulp-VM8Ug5gsrGeCQ59B\" data-title=\"Subscription Form - Popup #01\" data-width=\"540\" data-height=\"540\" data-close=\"on\" data-position=\"middle-center\" style=\"width: 540px; height: 540px; top: 50%; left: 50%; margin-left: -270px; margin-top: -270px; display: block;\">";
strVar += "<div class=\"ulp-content\" style=\"width: 540px; height: 540px;\">";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-442\" data-left=\"0\" data-top=\"0\" data-appearance=\"fade-in\" data-appearance-speed=\"1000\" data-appearance-delay=\"0\" data-width=\"700\" data-height=\"400\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 700px; height: 400px; font-size: 14px; left: 0px; top: 0px;\"><\/div>";
strVar += "<div class=\"ulp-layer ulp-animated ulp-bounceInDown\" id=\"ulp-layer-443\" data-left=\"0\" data-top=\"68\" data-appearance=\"bounceInDown\" data-appearance-speed=\"1000\" data-appearance-delay=\"0\" data-width=\"297\" data-height=\"345\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 297px; height: 345px; font-size: 14px; left: 0px; top: 68px; animation-duration: 1000ms; animation-delay: 0ms;\"><img src=\"http:\/\/witgetservice.com\/wdt\/images\/palma.png\" alt=\"\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-446\" data-left=\"200\" data-top=\"15\" data-appearance=\"slide-down\" data-appearance-speed=\"1000\" data-appearance-delay=\"700\" data-width=\"490\" data-font-size=\"28\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 490px; font-size: 28px; left: 200px; top: 15px;\">{WDT_EDT_W_TITLE}<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-447\" data-left=\"300\" data-top=\"80\" data-appearance=\"slide-right\" data-appearance-speed=\"1000\" data-appearance-delay=\"700\" data-width=\"300\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 300px; font-size: 14px; left: 300px; top: 80px;\"><img src=\"http:\/\/witgetservice.com\/wdt\/images\/oblako.png\" alt=\"\"><\/div>";
strVar += "<div class=\"ulp-layer ulp-animated ulp-bounceInUp\" id=\"ulp-layer-448\" data-left=\"500\" data-top=\"230\" data-appearance=\"bounceInUp\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"192\" data-height=\"192\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 192px; height: 192px; font-size: 14px; left: 500px; top: 230px; animation-duration: 1000ms; animation-delay: 200ms;\"><img src=\"http:\/\/witgetservice.com\/wdt\/images\/kater.png\" alt=\"\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-452\" data-left=\"130\" data-top=\"250\" data-appearance=\"slide-up\" data-appearance-speed=\"1000\" data-appearance-delay=\"1300\" data-width=\"510\" data-height=\"38\" data-font-size=\"16\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 510px; height: 38px; font-size: 16px; left: 130px; top: 250px;\"><a class=\"ulp-submit\" href=\"http:\/\/www.eurasiatravel.kz\/\" data-label=\"{WDT_EDT_BTN_TEXT}\" data-loading=\"{WDT_EDT_BTN_TEXT}\" target=\"_blank\" onclick=\"WdtActionFrmSubmit();\">{WDT_EDT_BTN_TEXT}<\/a><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-454\" data-left=\"681\" data-top=\"5\" data-appearance=\"slide-down\" data-appearance-speed=\"1000\" data-appearance-delay=\"2500\" data-width=\"10\" data-height=\"10\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 10px; height: 10px; font-size: 14px; left: 681px; top: 5px;\"><a href=\"#\" onClick=\"return ulp_self_close();\">x<\/a><\/div>";
strVar += "<div class=\"ulp-layer ulp-animated ulp-fadeInDown\" id=\"ulp-layer-455\" data-left=\"300\" data-top=\"95\" data-appearance=\"fadeInDown\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"300\" data-font-size=\"11\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 300px; font-size: 11px; left: 300px; top: 95px; animation-duration: 1000ms; animation-delay: 200ms;\">{WDT_EDT_W_TEXT}<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-456\" data-left=\"90\" data-top=\"60\" data-appearance=\"fade-in\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"700\" data-height=\"50\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 700px; height: 50px; font-size: 14px; left: 90px; top: 60px;\"><img src=\"http:\/\/witgetservice.com\/wdt\/images\/poloska.jpg\" alt=\"\"><\/div>";
strVar += "<\/div>";
strVar += "<\/div>";
strVar += "<form method=\"post\" id=\"WdtActFrm\" action=\"{WDT_ACTION}\" target=\"widget_iframe\">";
strVar += "<input type=\"hidden\" name=\"wdt_act_pereh\" value=\"1\"\/>";
strVar += "<\/form>";
strVar += "<script>";
strVar += "function WdtActionFrmSubmit(){";
strVar += "	$('#WdtActFrm').submit();";
strVar += "}";
strVar += "<\/script>";

$('#widget_div').html(strVar);