var strVar="";
strVar += "<script src=\"http:\/\/witgetservice.com\/wdt\/js\/ulp-jsonp4.js\"><\/script>";
strVar += "<link href=\"https:\/\/fonts.googleapis.com\/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic&amp;subset=cyrillic-ext,greek,vietnamese,latin-ext,cyrillic,latin,greek-ext\" rel=\"stylesheet\" type=\"text\/css\"><style>";
strVar += ".ulp-overlay {";
strVar += "position: fixed;";
strVar += "z-index: 1000000;";
strVar += "top: 0px;";
strVar += "left: 0px;";
strVar += "height: 100%;";
strVar += "width: 100%;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "position: fixed;";
strVar += "z-index: 1000001;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-inline-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-content {";
strVar += "position: relative;";
strVar += "}";
strVar += ".ulp-layer {";
strVar += "position: absolute;";
strVar += "box-sizing: border-box;";
strVar += "-moz-box-sizing: border-box;";
strVar += "-webkit-box-sizing: border-box;";
strVar += "-o-box-sizing: border-box;";
strVar += "-khtml-box-sizing: border-box;";
strVar += "text-align: justify;";
strVar += "line-height: 1.475;";
strVar += "}";
strVar += ".ulp-layer img {";
strVar += "max-width: 100% !important;";
strVar += "min-width: 0px !important;";
strVar += "margin: 0 !important;";
strVar += "padding: 0 !important;";
strVar += "border: none !important;";
strVar += "box-shadow: none !important;";
strVar += "-webkit-box-shadow: none !important;";
strVar += "-moz-box-shadow: none !important;";
strVar += "-ms-box-shadow: none !important;";
strVar += "-o-box-shadow: none !important;";
strVar += "}";
strVar += "#ulp-HF9cuNKpRrvJNb7w .ulp-submit,#ulp-HF9cuNKpRrvJNb7w .ulp-submit:visited{border-radius: 2px !important; background: #0147A3;border:1px solid #0147A3;background-image:linear-gradient(#013982,#0147A3);}#ulp-HF9cuNKpRrvJNb7w .ulp-submit:hover,#ulp-HF9cuNKpRrvJNb7w .ulp-submit:active{border-radius: 2px !important; background: #013982;border:1px solid #0147A3;background-image:linear-gradient(#0147A3,#013982);}#ulp-HF9cuNKpRrvJNb7w .ulp-input,#ulp-HF9cuNKpRrvJNb7w .ulp-input:hover,#ulp-HF9cuNKpRrvJNb7w .ulp-input:active,#ulp-HF9cuNKpRrvJNb7w .ulp-input:focus{border-width: 1px !important; border-radius: 2px !important; border-color:#444444;background-color:#FFFFFF !important;background-color:rgba(255,255,255,0.7) !important;}#ulp-HF9cuNKpRrvJNb7w-overlay{background:#969696;opacity:0.8;-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity='80')\";filter:alpha(opacity=\"80\");}#ulp-HF9cuNKpRrvJNb7w .ulp-submit-button,#ulp-HF9cuNKpRrvJNb7w .ulp-submit-button:visited,#ulp-HF9cuNKpRrvJNb7w .ulp-submit-button:hover,#ulp-HF9cuNKpRrvJNb7w .ulp-submit-button:active{border-radius: 2px !important;}#ulp-HF9cuNKpRrvJNb7w .ulp-submit-facebook,#ulp-HF9cuNKpRrvJNb7w .ulp-submit-facebook:visited{background: #3b5998;border:1px solid #3b5998;background-image:linear-gradient(#324b80,#3b5998);}#ulp-HF9cuNKpRrvJNb7w .ulp-submit-facebook:hover,#ulp-HF9cuNKpRrvJNb7w .ulp-submit-facebook:active{background: #324b80;border:1px solid #3b5998;background-image:linear-gradient(#3b5998,#324b80);}#ulp-HF9cuNKpRrvJNb7w .ulp-submit-google,#ulp-HF9cuNKpRrvJNb7w .ulp-submit-google:visited{background: #d34836;border:1px solid #d34836;background-image:linear-gradient(#b53e2f,#d34836);}#ulp-HF9cuNKpRrvJNb7w .ulp-submit-google:hover,#ulp-HF9cuNKpRrvJNb7w .ulp-submit-google:active{background: #b53e2f;border:1px solid #d34836;background-image:linear-gradient(#d34836,#b53e2f);}#ulp-layer-122,#ulp-layer-122 p,#ulp-layer-122 a,#ulp-layer-122 span,#ulp-layer-122 li,#ulp-layer-122 input,#ulp-layer-122 button,#ulp-layer-122 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-122{z-index:1000003;text-align:left;}#ulp-layer-123,#ulp-layer-123 p,#ulp-layer-123 a,#ulp-layer-123 span,#ulp-layer-123 li,#ulp-layer-123 input,#ulp-layer-123 button,#ulp-layer-123 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-123{z-index:1000007;text-align:left;}#ulp-layer-124,#ulp-layer-124 p,#ulp-layer-124 a,#ulp-layer-124 span,#ulp-layer-124 li,#ulp-layer-124 input,#ulp-layer-124 button,#ulp-layer-124 textarea {font-family:'Open Sans', arial;font-weight:400;color:#ffffff;text-shadow: #000000 1px 1px 1px;}#ulp-layer-124{z-index:1000007;text-align:center;padding: 10px 20px;}#ulp-layer-125,#ulp-layer-125 p,#ulp-layer-125 a,#ulp-layer-125 span,#ulp-layer-125 li,#ulp-layer-125 input,#ulp-layer-125 button,#ulp-layer-125 textarea {font-family:'arial', arial;font-weight:700;color:#ffffff;text-shadow: #3a3a3a 1px 1px 1px; text-decoration:none;}#ulp-layer-125{z-index:1000007;text-align:right;}<\/style> ";
strVar += "<div class=\"ulp-overlay\" id=\"ulp-HF9cuNKpRrvJNb7w-overlay\" style=\"display: block;\"><\/div>";
strVar += "<div class=\"ulp-window\" id=\"ulp-HF9cuNKpRrvJNb7w\" data-title=\"Video - Popup #02\" data-width=\"650\" data-height=\"400\" data-close=\"on\" data-position=\"middle-center\" style=\"width: 650px; height: 400px; top: 50%; left: 50%; margin-left: -325px; margin-top: -200px; display: block;\">";
strVar += "<div class=\"ulp-content\" style=\"width: 650px; height: 400px;\">";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-122\" data-left=\"0\" data-top=\"0\" data-appearance=\"fade-in\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"650\" data-height=\"400\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 650px; height: 400px; font-size: 14px; left: 0px; top: 0px;\"><img src=\"http:\/\/witgetservice.com\/wdt\/images\/macbook.png\" alt=\"\">{WDT_COPYRIGHT}<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-123\" data-left=\"80\" data-top=\"30\" data-appearance=\"slide-up\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"490\" data-height=\"320\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 490px; height: 320px; font-size: 14px; left: 80px; top: 30px;\">";
strVar += "<iframe width=\"100%\" height=\"100%\" src=\"\/\/www.youtube.com\/embed\/mUlvUhMhiFk?autoplay=1\" frameborder=\"0\" allowfullscreen=\"\"><\/iframe>";
strVar += "<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-124\" data-left=\"0\" data-top=\"-40\" data-appearance=\"slide-down\" data-appearance-speed=\"1000\" data-appearance-delay=\"1000\" data-width=\"650\" data-font-size=\"24\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 650px; font-size: 24px; left: 0px; top: -40px;\">ВИДЕО О НАС<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-125\" data-left=\"0\" data-top=\"-25\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"1000\" data-width=\"650\" data-height=\"25\" data-font-size=\"20\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 650px; height: 25px; font-size: 20px; left: 0px; top: -25px;\"><a href=\"#\" onclick=\"return ulp_self_close();\">×<\/a><\/div>";
strVar += "<\/div>";
strVar += "<\/div>";
$('#widget_div').html(strVar);