var strVar="";
strVar += "<script src=\"http:\/\/witgetservice.com\/wdt\/js\/ulp-jsonp16.js\"><\/script>";
strVar += "<script>";
strVar += "var ulp_ajax_url = 'http:\/\/witgetservice.com\/wdt\/ajax7.php{WDT_U_ID}'; ";
strVar += "<\/script>";
strVar += "";
strVar += "<style>";
strVar += ".ulp-overlay {";
strVar += "position: fixed;";
strVar += "z-index: 1000000;";
strVar += "top: 0px;";
strVar += "left: 0px;";
strVar += "height: 100%;";
strVar += "width: 100%;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "position: fixed;";
strVar += "z-index: 1000001;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-inline-window {";
strVar += "font-size: 14px;";
strVar += "font-family: arial, verdana;";
strVar += "text-align: left;";
strVar += "display: none;";
strVar += "}";
strVar += ".ulp-content {";
strVar += "position: relative;";
strVar += "}";
strVar += ".ulp-layer {";
strVar += "position: absolute;";
strVar += "box-sizing: border-box;";
strVar += "-moz-box-sizing: border-box;";
strVar += "-webkit-box-sizing: border-box;";
strVar += "-o-box-sizing: border-box;";
strVar += "-khtml-box-sizing: border-box;";
strVar += "text-align: justify;";
strVar += "line-height: 1.475;";
strVar += "}";
strVar += ".ulp-layer img {";
strVar += "max-width: 100% !important;";
strVar += "min-width: 0px !important;";
strVar += "margin: 0 !important;";
strVar += "padding: 0 !important;";
strVar += "border: none !important;";
strVar += "box-shadow: none !important;";
strVar += "-webkit-box-shadow: none !important;";
strVar += "-moz-box-shadow: none !important;";
strVar += "-ms-box-shadow: none !important;";
strVar += "-o-box-shadow: none !important;";
strVar += "}";
strVar += ".ulp-input {";
strVar += "-moz-border-radius: 2px !important;";
strVar += "-webkit-border-radius: 2px !important;";
strVar += "-o-border-radius: 2px !important;";
strVar += "-ms-border-radius: 2px !important;";
strVar += "-khtml-border-radius: 2px !important;";
strVar += "border-radius: 2px !important;";
strVar += "vertical-align: middle !important;";
strVar += "border-width: 1px !important;";
strVar += "border-style: solid !important;";
strVar += "border-color: #888;";
strVar += "border-spacing: 0 !important;";
strVar += "clear: both !important;	";
strVar += "width: 100% !important;";
strVar += "margin: 0px !important;";
strVar += "-moz-box-sizing: border-box !important;";
strVar += "-webkit-box-sizing: border-box !important;";
strVar += "-ms-box-sizing: border-box !important;";
strVar += "box-sizing: border-box !important;";
strVar += "height: 100% !important;";
strVar += "background: #FFFFFF;";
strVar += "margin: 0 !important;";
strVar += "padding: 0px 6px !important;";
strVar += "line-height: 1.5 !important;";
strVar += "background: rgba(255,255,255,0.8);";
strVar += "-moz-box-shadow: none !important;";
strVar += "-webkit-box-shadow: none !important;";
strVar += "-o-box-shadow: none !important;";
strVar += "-ms-box-shadow: none !important;";
strVar += "box-shadow: none !important;";
strVar += "font-size: inherit !important;";
strVar += "}";
strVar += ".ulp-input-error {";
strVar += "background-image: url(http:\/\/witgetservice.com\/wdt\/images\/error.png);";
strVar += "background-position: 100% 50%;";
strVar += "background-repeat: no-repeat;";
strVar += "border-color: red !important;";
strVar += "}";
strVar += ".ulp-submit, .ulp-submit:visited, .ulp-submit-button, .ulp-submit-button:visited {";
strVar += "text-decoration: none !important;";
strVar += "font-size: inherit !important;";
strVar += "text-shadow: 0 -1px 1px rgba(0,0,0,.25);";
strVar += "background-color: #{WDT_EDT_BTN_COLOR2};";
strVar += "background-repeat: repeat-x;";
strVar += "background-image: -moz-linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "background-image: -ms-linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "background-image: -webkit-linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "background-image: -o-linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "background-image: linear-gradient(#{WDT_EDT_BTN_COLOR1},#{WDT_EDT_BTN_COLOR2});";
strVar += "transition-duration: .3s;";
strVar += "-moz-transition-duration: .3s;";
strVar += "-webkit-transition-duration: .3s;";
strVar += "-o-transition-duration: .3s;";
strVar += "-khtml-transition-duration: .3s;";
strVar += "filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#{WDT_EDT_BTN_COLOR1}',endColorstr='#{WDT_EDT_BTN_COLOR2}',GradientType=0);";
strVar += "border: 1px solid #019ad2;";
strVar += "width: auto;";
strVar += "white-space: nowrap;";
strVar += "height: auto;";
strVar += "position: relative;";
strVar += "display: inline-block;";
strVar += "padding: 5px 20px;";
strVar += "line-height: 1.5;";
strVar += "cursor: pointer;";
strVar += "-moz-border-radius: 2px;";
strVar += "-webkit-border-radius: 2px;";
strVar += "-o-border-radius: 2px;";
strVar += "-ms-border-radius: 2px;";
strVar += "-khtml-border-radius: 2px;";
strVar += "border-radius: 2px;";
strVar += "margin: 0;";
strVar += "-webkit-box-shadow: none;";
strVar += "-moz-box-shadow: none;";
strVar += "-o-box-shadow: none;";
strVar += "-ms-box-shadow: none;";
strVar += "box-shadow: none;";
strVar += "}";
strVar += ".ulp-window a {";
strVar += "text-decoration: none !important;";
strVar += "}";
strVar += ".ulp-submit:hover, .ulp-submit:active, .ulp-submit-button:hover, .ulp-submit-button:active {";
strVar += "background-color:#{WDT_EDT_BTN_COLOR4};";
strVar += "background-repeat:repeat-x;";
strVar += "background-image:-moz-linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "background-image:-ms-linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "background-image:-webkit-linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "background-image:-o-linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "background-image:linear-gradient(#{WDT_EDT_BTN_COLOR3},#{WDT_EDT_BTN_COLOR4});";
strVar += "filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#{WDT_EDT_BTN_COLOR3}',endColorstr='#{WDT_EDT_BTN_COLOR4}',GradientType=0);";
strVar += "border: 1px solid #019ad2;";
strVar += "-webkit-box-shadow: none;";
strVar += "-moz-box-shadow: none;";
strVar += "-o-box-shadow: none;";
strVar += "-ms-box-shadow: none;";
strVar += "box-shadow: none;";
strVar += "}";
strVar += "#ulp-zOjhqUEoIS2Ytl8q .ulp-submit,#ulp-zOjhqUEoIS2Ytl8q .ulp-submit:visited{border-radius: 2px !important; background: #{WDT_EDT_BTN_COLOR1};border:1px solid #{WDT_EDT_BTN_COLOR1};background-image:linear-gradient(#{WDT_EDT_BTN_COLOR2},#{WDT_EDT_BTN_COLOR1});}#ulp-zOjhqUEoIS2Ytl8q .ulp-submit:hover,#ulp-zOjhqUEoIS2Ytl8q .ulp-submit:active{border-radius: 2px !important; background: #{WDT_EDT_BTN_COLOR3};border:1px solid #{WDT_EDT_BTN_COLOR4};background-image:linear-gradient(#{WDT_EDT_BTN_COLOR4},#{WDT_EDT_BTN_COLOR3});}#ulp-zOjhqUEoIS2Ytl8q .ulp-input,#ulp-zOjhqUEoIS2Ytl8q .ulp-input:hover,#ulp-zOjhqUEoIS2Ytl8q .ulp-input:active,#ulp-zOjhqUEoIS2Ytl8q .ulp-input:focus{border-width: 1px !important; border-radius: 2px !important; border-color:#1a3a00;background-color:#103500 !important;background-color:rgba(16,53,0,0.5) !important;}#ulp-zOjhqUEoIS2Ytl8q-overlay{background:#{WDT_EDT_BG_COLOR};opacity:0.8;-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity='80')\";filter:alpha(opacity=\"80\");}#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-button,#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-button:visited,#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-button:hover,#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-button:active{border-radius: 2px !important;}#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-facebook,#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-facebook:visited{background: #3b5998;border:1px solid #3b5998;background-image:linear-gradient(#324b80,#3b5998);}#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-facebook:hover,#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-facebook:active{background: #324b80;border:1px solid #3b5998;background-image:linear-gradient(#3b5998,#324b80);}#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-google,#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-google:visited{background: #d34836;border:1px solid #d34836;background-image:linear-gradient(#b53e2f,#d34836);}#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-google:hover,#ulp-zOjhqUEoIS2Ytl8q .ulp-submit-google:active{background: #b53e2f;border:1px solid #d34836;background-image:linear-gradient(#d34836,#b53e2f);}#ulp-layer-299,#ulp-layer-299 p,#ulp-layer-299 a,#ulp-layer-299 span,#ulp-layer-299 li,#ulp-layer-299 input,#ulp-layer-299 button,#ulp-layer-299 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-299{background-color:#d6d6d6;background-color:rgba(214,214,214,0.9);background-image:url(http:\/\/widgets\/images\/default\/graybg03.png);background-repeat:repeat;z-index:1000003;text-align:left;box-shadow: rgba(32,32,32,1) 0 4px 20px; border-radius: 3px;}#ulp-layer-300,#ulp-layer-300 p,#ulp-layer-300 a,#ulp-layer-300 span,#ulp-layer-300 li,#ulp-layer-300 input,#ulp-layer-300 button,#ulp-layer-300 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-300{z-index:1000003;text-align:left;box-shadow: rgba(240,240,240,1) 0 0 60px inset; border-radius: 3px;}#ulp-layer-301,#ulp-layer-301 p,#ulp-layer-301 a,#ulp-layer-301 span,#ulp-layer-301 li,#ulp-layer-301 input,#ulp-layer-301 button,#ulp-layer-301 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-301{z-index:1000007;text-align:left;}#ulp-layer-302,#ulp-layer-302 p,#ulp-layer-302 a,#ulp-layer-302 span,#ulp-layer-302 li,#ulp-layer-302 input,#ulp-layer-302 button,#ulp-layer-302 textarea {font-family:'arial', arial;font-weight:400;color:#000000;}#ulp-layer-302{background-color:#{WDT_EDT_W_COLOR};z-index:1000003;text-align:left;box-shadow: rgba(0,0,0,0.3) 0 0 60px inset; border-radius: 0 3px 3px 0;}#ulp-layer-303,#ulp-layer-303 p,#ulp-layer-303 a,#ulp-layer-303 span,#ulp-layer-303 li,#ulp-layer-303 input,#ulp-layer-303 button,#ulp-layer-303 textarea {font-family:'Open Sans', arial;font-weight:400;color:#{WDT_EDT_TEXT_COLOR};text-shadow: #000000 1px 1px 1px;}#ulp-layer-303{z-index:1000007;text-align:center;}#ulp-layer-304,#ulp-layer-304 p,#ulp-layer-304 a,#ulp-layer-304 span,#ulp-layer-304 li,#ulp-layer-304 input,#ulp-layer-304 button,#ulp-layer-304 textarea {font-family:'Open Sans', arial;font-weight:400;color:#{WDT_EDT_TEXT_COLOR};text-shadow: #000000 1px 1px 1px;}#ulp-layer-304{z-index:1000007;text-align:justify;}#ulp-layer-305,#ulp-layer-305 p,#ulp-layer-305 a,#ulp-layer-305 span,#ulp-layer-305 li,#ulp-layer-305 input,#ulp-layer-305 button,#ulp-layer-305 textarea {font-family:'Open Sans', arial;font-weight:400;color:#ffffff;text-shadow: #000000 1px 1px 1px;}#ulp-layer-305{z-index:1000007;text-align:justify;}#ulp-layer-306,#ulp-layer-306 p,#ulp-layer-306 a,#ulp-layer-306 span,#ulp-layer-306 li,#ulp-layer-306 input,#ulp-layer-306 button,#ulp-layer-306 textarea {font-family:'Open Sans', arial;font-weight:400;color:#ffffff;text-shadow: #000000 1px 1px 1px;}#ulp-layer-306{z-index:1000007;text-align:justify;}#ulp-layer-307,#ulp-layer-307 p,#ulp-layer-307 a,#ulp-layer-307 span,#ulp-layer-307 li,#ulp-layer-307 input,#ulp-layer-307 button,#ulp-layer-307 textarea {font-family:'Open Sans', arial;font-weight:400;color:#ffffff;text-shadow: #000000 1px 1px 1px;}#ulp-layer-307{z-index:1000007;text-align:center;}#ulp-layer-308,#ulp-layer-308 p,#ulp-layer-308 a,#ulp-layer-308 span,#ulp-layer-308 li,#ulp-layer-308 input,#ulp-layer-308 button,#ulp-layer-308 textarea {font-family:'Open Sans', arial;font-weight:400;color:#{WDT_EDT_TEXT_COLOR};text-shadow: #000000 1px 1px 1px;}#ulp-layer-308{z-index:1000007;text-align:center;}#ulp-layer-309,#ulp-layer-309 p,#ulp-layer-309 a,#ulp-layer-309 span,#ulp-layer-309 li,#ulp-layer-309 input,#ulp-layer-309 button,#ulp-layer-309 textarea {font-family:'arial', arial;font-weight:400;color:#ffffff;text-shadow: #000000 1px 1px 1px;}#ulp-layer-309{z-index:1000007;text-align:right;}<\/style>";
strVar += "<div class=\"ulp-overlay\" id=\"ulp-zOjhqUEoIS2Ytl8q-overlay\" style=\"display: block;\"><\/div>";
strVar += "<div class=\"ulp-window\" id=\"ulp-zOjhqUEoIS2Ytl8q\" data-title=\"Subscription Form - Popup #14\" data-width=\"640\" data-height=\"300\" data-close=\"on\" data-position=\"middle-center\" style=\"width: 640px; height: 300px; top: 50%; left: 50%; margin-left: -320px; margin-top: -150px; display: block;\">";
strVar += "<div class=\"ulp-content\" style=\"width: 640px; height: 300px;\">";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-299\" data-left=\"0\" data-top=\"0\" data-appearance=\"fade-in\" data-appearance-speed=\"1000\" data-appearance-delay=\"0\" data-width=\"640\" data-height=\"300\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 640px; height: 300px; font-size: 14px; left: 0px; top: 0px;\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-300\" data-left=\"0\" data-top=\"0\" data-appearance=\"fade-in\" data-appearance-speed=\"1000\" data-appearance-delay=\"0\" data-width=\"640\" data-height=\"300\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 640px; height: 300px; font-size: 14px; left: 0px; top: 0px;\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-301\" data-left=\"70\" data-top=\"55\" data-appearance=\"slide-right\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"192\" data-height=\"192\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 192px; height: 192px; font-size: 14px; left: 70px; top: 55px;\"><img src=\"{WDT_EDT_IMG}\" alt=\"\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-302\" data-left=\"340\" data-top=\"0\" data-appearance=\"fade-in\" data-appearance-speed=\"1000\" data-appearance-delay=\"200\" data-width=\"300\" data-height=\"300\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 300px; height: 300px; font-size: 14px; left: 340px; top: 0px;\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-303\" data-left=\"340\" data-top=\"15\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"500\" data-width=\"300\" data-font-size=\"20\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 300px; font-size: 20px; left: 340px; top: 15px;\">{WDT_EDT_W_TITLE}<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-304\" data-left=\"360\" data-top=\"60\" data-appearance=\"slide-left\" data-appearance-speed=\"1000\" data-appearance-delay=\"700\" data-width=\"260\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 260px; font-size: 14px; left: 360px; top: 60px;\">{WDT_EDT_W_TEXT}<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-305\" data-left=\"360\" data-top=\"140\" data-appearance=\"slide-up\" data-appearance-speed=\"1000\" data-appearance-delay=\"900\" data-width=\"260\" data-height=\"34\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 260px; height: 34px; font-size: 14px; left: 360px; top: 140px;\"><input class=\"ulp-input\" type=\"text\" name=\"ulp-name\" placeholder=\"{WDT_EDT_INP_PLACE1}\" value=\"\" onfocus=\"jQuery(this).removeClass('ulp-input-error');\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-306\" data-left=\"360\" data-top=\"180\" data-appearance=\"slide-up\" data-appearance-speed=\"1000\" data-appearance-delay=\"1100\" data-width=\"260\" data-height=\"34\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 260px; height: 34px; font-size: 14px; left: 360px; top: 180px;\"><input class=\"ulp-input\" type=\"text\" name=\"ulp-email\" placeholder=\"{WDT_EDT_INP_PLACE2}\" value=\"\" onfocus=\"jQuery(this).removeClass('ulp-input-error');\"><input type=\"hidden\" name=\"ulp-w_id\" value=\"{WDT_W_ID}\"><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-307\" data-left=\"360\" data-top=\"225\" data-appearance=\"slide-up\" data-appearance-speed=\"1000\" data-appearance-delay=\"1300\" data-width=\"260\" data-height=\"38\" data-font-size=\"14\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 260px; height: 38px; font-size: 14px; left: 360px; top: 225px;\"><a class=\"ulp-submit\" onclick=\"return ulp_subscribe(this);\" data-label=\"{WDT_EDT_BTN_TEXT}\" data-loading=\"{WDT_EDT_BTN_TEXT2}\">{WDT_EDT_BTN_TEXT}<\/a><\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-308\" data-left=\"340\" data-top=\"270\" data-appearance=\"slide-up\" data-appearance-speed=\"1000\" data-appearance-delay=\"1700\" data-width=\"300\" data-font-size=\"12\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 300px; font-size: 12px; left: 340px; top: 270px;\">{WDT_EDT_W_COMENT}<\/div>";
strVar += "<div class=\"ulp-layer\" id=\"ulp-layer-309\" data-left=\"600\" data-top=\"-30\" data-appearance=\"slide-down\" data-appearance-speed=\"1000\" data-appearance-delay=\"2500\" data-width=\"40\" data-height=\"20\" data-font-size=\"24\" data-scrollbar=\"off\" data-confirmation=\"off\" style=\"width: 40px; height: 20px; font-size: 24px; left: 600px; top: -30px;\"><a href=\"#\" onclick=\"return ulp_self_close();\">×<\/a><\/div>";
strVar += "<\/div>";
strVar += "<\/div>";

$('#widget_div').html(strVar);